"""empty message

Revision ID: 25ea9b86dd82
Revises: 8b61761122b3
Create Date: 2020-05-03 09:55:48.847548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "25ea9b86dd82"
down_revision = "8b61761122b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cohort",
        sa.Column("campus", sa.String(), nullable=False, server_default="Remote LA"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cohort", "campus")
    # ### end Alembic commands ###
