users = [
    {
        "email": "james@jamesliu.cc",
        "first_name": "James",
        "last_name": "liu",
        "password": "password",
    },
    {
        "email": "echastenet0@google.fr",
        "first_name": "Eduino",
        "last_name": "Chastenet",
        "password": "Euphorbiaceae",
    },
    {
        "email": "tbaudou1@ifeng.com",
        "first_name": "Trudey",
        "last_name": "Baudou",
        "password": "Scrophulariaceae",
    },
    {
        "email": "faubrey2@lulu.com",
        "first_name": "Filia",
        "last_name": "Aubrey",
        "password": "Mycoblastaceae",
    },
    {
        "email": "mextill3@shutterfly.com",
        "first_name": "Meggi",
        "last_name": "Extill",
        "password": "Garryaceae",
    },
    {
        "email": "pburston4@ca.gov",
        "first_name": "Preston",
        "last_name": "Burston",
        "password": "Malpighiaceae",
    },
    {
        "email": "imaides5@narod.ru",
        "first_name": "Ingamar",
        "last_name": "Maides",
        "password": "Myrtaceae",
    },
    {
        "email": "eeadie6@shinystat.com",
        "first_name": "Eduardo",
        "last_name": "Eadie",
        "password": "Hydrophyllaceae",
    },
    {
        "email": "esaiz7@google.cn",
        "first_name": "Ephrem",
        "last_name": "Saiz",
        "password": "Hydrophyllaceae",
    },
    {
        "email": "cwace8@360.cn",
        "first_name": "Cullin",
        "last_name": "Wace",
        "password": "Scrophulariaceae",
    },
    {
        "email": "ocaffery9@live.com",
        "first_name": "Obediah",
        "last_name": "Caffery",
        "password": "Poaceae",
    },
    {
        "email": "ezellanda@360.cn",
        "first_name": "Ermina",
        "last_name": "Zelland",
        "password": "Trapeliaceae",
    },
    {
        "email": "spolgreenb@digg.com",
        "first_name": "Selena",
        "last_name": "Polgreen",
        "password": "Hydrophyllaceae",
    },
    {
        "email": "cspillmanc@marriott.com",
        "first_name": "Chaddy",
        "last_name": "Spillman",
        "password": "Cyperaceae",
    },
    {
        "email": "shillittd@reuters.com",
        "first_name": "Sigismund",
        "last_name": "Hillitt",
        "password": "Graphidaceae",
    },
    {
        "email": "audye@answers.com",
        "first_name": "Ahmed",
        "last_name": "Udy",
        "password": "Brassicaceae",
    },
    {
        "email": "calmeyf@redcross.org",
        "first_name": "Clint",
        "last_name": "Almey",
        "password": "Crassulaceae",
    },
    {
        "email": "cledinghamg@state.tx.us",
        "first_name": "Clem",
        "last_name": "Ledingham",
        "password": "Asteraceae",
    },
    {
        "email": "smassingberdh@patch.com",
        "first_name": "Silvester",
        "last_name": "Massingberd",
        "password": "Rosaceae",
    },
    {
        "email": "wgalvani@discovery.com",
        "first_name": "Willard",
        "last_name": "Galvan",
        "password": "Poaceae",
    },
    {
        "email": "gcorneliusj@redcross.org",
        "first_name": "Gualterio",
        "last_name": "Cornelius",
        "password": "Portulacaceae",
    },
    {
        "email": "dwodhamk@booking.com",
        "first_name": "Doralyn",
        "last_name": "Wodham",
        "password": "Cyperaceae",
    },
    {
        "email": "cwinsletl@epa.gov",
        "first_name": "Chane",
        "last_name": "Winslet",
        "password": "Lamiaceae",
    },
    {
        "email": "mcheekm@woothemes.com",
        "first_name": "Malchy",
        "last_name": "Cheek",
        "password": "Lobariaceae",
    },
    {
        "email": "strimmingn@creativecommons.org",
        "first_name": "Shae",
        "last_name": "Trimming",
        "password": "Cactaceae",
    },
    {
        "email": "ezumbuscho@weather.com",
        "first_name": "Evangeline",
        "last_name": "Zumbusch",
        "password": "Rubiaceae",
    },
    {
        "email": "lallixp@1und1.de",
        "first_name": "Laverne",
        "last_name": "Allix",
        "password": "Amblystegiaceae",
    },
    {
        "email": "oeyreeq@addtoany.com",
        "first_name": "Ode",
        "last_name": "Eyree",
        "password": "Poaceae",
    },
    {
        "email": "dknapmanr@businesswire.com",
        "first_name": "Dev",
        "last_name": "Knapman",
        "password": "Asteraceae",
    },
    {
        "email": "tsyddons@cdc.gov",
        "first_name": "Tate",
        "last_name": "Syddon",
        "password": "Amaranthaceae",
    },
    {
        "email": "hhouldt@blinklist.com",
        "first_name": "Herman",
        "last_name": "Hould",
        "password": "Euphorbiaceae",
    },
    {
        "email": "amouldenu@state.gov",
        "first_name": "Arther",
        "last_name": "Moulden",
        "password": "Poaceae",
    },
    {
        "email": "acurtisv@hexun.com",
        "first_name": "Augusto",
        "last_name": "Curtis",
        "password": "Poaceae",
    },
    {
        "email": "dbrikw@eventbrite.com",
        "first_name": "Dorothee",
        "last_name": "Brik",
        "password": "Hydrophyllaceae",
    },
    {
        "email": "dfarninx@aboutads.info",
        "first_name": "Drucill",
        "last_name": "Farnin",
        "password": "Cistaceae",
    },
    {
        "email": "smcfetridgey@apache.org",
        "first_name": "Stanton",
        "last_name": "McFetridge",
        "password": "Caryophyllaceae",
    },
    {
        "email": "alippingwellz@netvibes.com",
        "first_name": "Alix",
        "last_name": "Lippingwell",
        "password": "Araceae",
    },
    {
        "email": "vsygroves10@gmpg.org",
        "first_name": "Vi",
        "last_name": "Sygroves",
        "password": "Cactaceae",
    },
    {
        "email": "tmalacrida11@oakley.com",
        "first_name": "Tamra",
        "last_name": "Malacrida",
        "password": "Parmeliaceae",
    },
    {
        "email": "mcopner12@dell.com",
        "first_name": "Mohammed",
        "last_name": "Copner",
        "password": "Asteraceae",
    },
    {
        "email": "gvear13@google.co.uk",
        "first_name": "Gerry",
        "last_name": "Vear",
        "password": "Brassicaceae",
    },
]
